--🔹 GROUP BY

--Find the total bill amount generated by each patient using bills and patients.
select patients.patient_id, patients.patient_name, sum(bills.totalamount) as  total_bill_amount
from patients
join bills
on patients.patient_id = bills.patient_id
group by patients.patient_id
,patients.patient_name

--Find the number of appointments handled by each doctor.
select doctors.doctor_id,doctors.doctor_name,count(appointments.status) as appointment_handled_by_doctor
from doctors
join appointments
on doctors.doctor_id=appointments.doctor_id
group by doctors.doctor_id,doctors.doctor_name

--Find patients whose total bill amount is greater than 5000.

select totalamount
from bills
where totalamount>5000
